---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rideeasy
  namespace: rideeasy-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rideeasy
  template:
    metadata:
      labels:
        env1: dev
        app: rideeasy
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: rideeasy
        image: snaidu/rideeasy:1
        imagePullPolicy: "Always"
        ports:
          - containerPort: 8080
            protocol: TCP
