---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rideeasy
  namespace: rideeasy-qa
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rideeasy
  template:
    metadata:
      labels:
        env1: qa
        app: rideeasy
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: rideeasy
        image: 548633617490.dkr.ecr.us-east-1.amazonaws.com/qarideeasy:1
        imagePullPolicy: "Always"
        ports:
          - containerPort: 8080
            protocol: TCP
