---
apiVersion: v1
kind: Service
metadata:
  name: rideeasy-svc
  namespace: rideeasy-qa
spec:
  selector:
    env1: qa
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30005
  type: LoadBalancer
