---
apiVersion: v1
kind: Service
metadata:
  name: rideeasy-svc
  namespace: rideeasy-dev
spec:
  selector:
    env1: dev
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30004
  type: LoadBalancer
